-- Copyright (c) 2015 Blast Analytics & Marketing. All rights reserved.
--
-- This program is licensed to you under the Apache License Version 2.0,
-- and you may not use this file except in compliance with the Apache License Version 2.0.
-- You may obtain a copy of the Apache License Version 2.0 at http://www.apache.org/licenses/LICENSE-2.0.html.
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the Apache License Version 2.0 is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the Apache License Version 2.0 for the specific language governing permissions and limitations there under.
--
-- Version:     1.0
-- URL:         -
--
-- Authors:     Joao Correia <jcorreia@blastam.com>
-- Copyright:   Copyright (c) 2015 Blast Analytics & Marketing
-- License:     Apache License Version 2.0

SELECT
  STRFTIME_UTC_USEC(SEC_TO_TIMESTAMP(visitStartTime+ hits.time/1000),"%Y-%m-%d %H:%M:%S") as hit.timestamp,  
  -- ROUND(visitStartTime + hits.time/1000) as hits.timestamp,   /* Use for UNIX timestamp instead of timestamp */
  visitNumber,
  visitId,
  fullVisitorId,
  STRFTIME_UTC_USEC(SEC_TO_TIMESTAMP(visitStartTime),"%Y-%m-%d %H:%M:%S") as hit.visitStartTime,  
  LEFT(date,4)+"-"+SUBSTR(date,5,2)+"-"+RIGHT(date,2) as date,
  trafficSource.referralPath,
  trafficSource.campaign,
  trafficSource.source,
  trafficSource.medium,
  trafficSource.keyword,
  trafficSource.adContent,
  device.browser,
  device.browserVersion,
  device.operatingSystem,
  device.operatingSystemVersion,
  device.isMobile,
  device.mobileDeviceBranding, /* Only Availabe is later schemas */
  device.flashVersion,
  device.javaEnabled,
  device.language,
  device.screenColors,
  device.screenResolution,
  device.deviceCategory,
  geoNetwork.continent,
  geoNetwork.subContinent,
  geoNetwork.country,
  geoNetwork.region,
  geoNetwork.metro
  hits.type,
  hits.social.socialInteractionNetwork,
  hits.social.socialInteractionAction,
  hits.hitNumber,
  (hits.time/1000) as hits.time, /* Converted to seconds */
  hits.hour,
  hits.minute,
  hits.isSecure,
  hits.isInteraction,
  hits.referer,
  hits.page.pagePath,
  hits.page.hostname,
  hits.page.pageTitle,
  hits.page.searchKeyword,
  hits.page.searchCategory,

  -- Ecommerce
  hits.transaction.transactionId,
  hits.transaction.transactionRevenue,
  hits.transaction.transactionTax,
  hits.transaction.transactionShipping,
  hits.transaction.affiliation,
  hits.transaction.currencyCode,
  hits.transaction.localTransactionRevenue,
  hits.transaction.localTransactionTax,
  hits.transaction.localTransactionShipping,
  hits.transaction.transactionCoupon,
  hits.item.transactionId,
  hits.item.productName,
  hits.item.productCategory,
  hits.item.productSku,
  hits.item.itemQuantity,
  hits.item.itemRevenue,
  hits.item.currencyCode,
  hits.item.localItemRevenue,

  -- Enhanced Ecommerce
  hits.eCommerceAction.action_type, 
  hits.eCommerceAction.step,
  hits.eCommerceAction.option,

  hits.product.productSKU, 
  hits.product.v2ProductName, 
  hits.product.v2ProductCategory, 
  hits.product.productVariant, 
  hits.product.productBrand, 
  hits.product.productRevenue, 
  hits.product.localProductRevenue, 
  hits.product.productPrice, 
  hits.product.localProductPrice, 
  hits.product.productQuantity, 
  hits.product.productRefundAmount, 
  hits.product.localProductRefundAmount, 
  hits.product.isImpression,

  hits.refund.refundAmount,
  hits.refund.localRefundAmount,

  -- Promotion
  hits.promotion.promoId,
  hits.promotion.promoName,
  hits.promotion.promoCreative,
  hits.promotion.promoPosition,

  -- Mobile App
  hits.contentInfo.contentDescription,
  hits.appInfo.name,
  hits.appInfo.version,
  hits.appInfo.id,
  hits.appInfo.installerId,
  hits.appInfo.appInstallerId,
  hits.appInfo.appName,
  hits.appInfo.appVersion,
  hits.appInfo.appId,
  hits.appInfo.screenName,
  hits.appInfo.landingScreenName,
  hits.appInfo.exitScreenName,
  hits.appInfo.screenDepth,
  hits.exceptionInfo.description,
  hits.exceptionInfo.isFatal,

  -- Events
  hits.eventInfo.eventCategory,
  hits.eventInfo.eventAction,
  hits.eventInfo.eventLabel,
  hits.eventInfo.eventValue,
  
   -- Custom Dimensions (Add your custom dimensions by adding a line for each dimension)
  MAX(IF (hits.customDimensions.index = 1, hits.customDimensions.value,  NULL)) WITHIN RECORD AS dimension1,
  MAX(IF (hits.customDimensions.index = 2, hits.customDimensions.value,  NULL)) WITHIN RECORD AS dimension2,
  MAX(IF (hits.customDimensions.index = 3, hits.customDimensions.value,  NULL)) WITHIN RECORD AS dimension3,
  
  -- Custom Metrics (Add your custom metrics by adding a line for each metric)
  MAX(IF (hits.customMetrics.index = 1, hits.customMetrics.value,  NULL)) WITHIN RECORD AS metric1,
  MAX(IF (hits.customMetrics.index = 2, hits.customMetrics.value,  NULL)) WITHIN RECORD AS metric2,
  MAX(IF (hits.customMetrics.index = 3, hits.customMetrics.value,  NULL)) WITHIN RECORD AS metric3,
  
  -- Custom Variables (Use only the )
  MAX(IF (hits.customVariables.index = 1, hits.customVariables.customVarName,   NULL)) WITHIN RECORD AS cv1Key,
  MAX(IF (hits.customVariables.index = 1, hits.customVariables.customVarValue,  NULL)) WITHIN RECORD AS cv1Value,
  MAX(IF (hits.customVariables.index = 2, hits.customVariables.customVarName,   NULL)) WITHIN RECORD AS cv2Key,
  MAX(IF (hits.customVariables.index = 2, hits.customVariables.customVarValue,  NULL)) WITHIN RECORD AS cv2Value,
  MAX(IF (hits.customVariables.index = 3, hits.customVariables.customVarName,   NULL)) WITHIN RECORD AS cv3Key,
  MAX(IF (hits.customVariables.index = 3, hits.customVariables.customVarValue,  NULL)) WITHIN RECORD AS cv3Value,
  MAX(IF (hits.customVariables.index = 4, hits.customVariables.customVarName,   NULL)) WITHIN RECORD AS cv4Key,
  MAX(IF (hits.customVariables.index = 4, hits.customVariables.customVarValue,  NULL)) WITHIN RECORD AS cv4Value,
  MAX(IF (hits.customVariables.index = 5, hits.customVariables.customVarName,   NULL)) WITHIN RECORD AS cv5Key,
  MAX(IF (hits.customVariables.index = 5, hits.customVariables.customVarValue,  NULL)) WITHIN RECORD AS cv5Value,
  MAX(IF (hits.customVariables.index = 6, hits.customVariables.customVarName,   NULL)) WITHIN RECORD AS cv6Key,
  MAX(IF (hits.customVariables.index = 6, hits.customVariables.customVarValue,  NULL)) WITHIN RECORD AS cv6Value,
  MAX(IF (hits.customVariables.index = 7, hits.customVariables.customVarName,   NULL)) WITHIN RECORD AS cv7Key,
  MAX(IF (hits.customVariables.index = 7, hits.customVariables.customVarValue,  NULL)) WITHIN RECORD AS cv7Value,
  MAX(IF (hits.customVariables.index = 8, hits.customVariables.customVarName,   NULL)) WITHIN RECORD AS cv8Key,
  MAX(IF (hits.customVariables.index = 8, hits.customVariables.customVarValue,  NULL)) WITHIN RECORD AS cv8Value,
  MAX(IF (hits.customVariables.index = 9, hits.customVariables.customVarName,   NULL)) WITHIN RECORD AS cv9Key,
  MAX(IF (hits.customVariables.index = 9, hits.customVariables.customVarValue,  NULL)) WITHIN RECORD AS cv9Value, 
  MAX(IF (hits.customVariables.index = 10, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv10Key,
  MAX(IF (hits.customVariables.index = 10, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv10Value,  
  MAX(IF (hits.customVariables.index = 11, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv11Key,
  MAX(IF (hits.customVariables.index = 11, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv11Value,  
  MAX(IF (hits.customVariables.index = 12, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv12Key,
  MAX(IF (hits.customVariables.index = 12, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv12Value,  
  MAX(IF (hits.customVariables.index = 13, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv13Key,
  MAX(IF (hits.customVariables.index = 13, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv13Value,  
  MAX(IF (hits.customVariables.index = 14, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv14Key,
  MAX(IF (hits.customVariables.index = 14, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv14Value,  
  MAX(IF (hits.customVariables.index = 15, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv15Key,
  MAX(IF (hits.customVariables.index = 15, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv15Value,  
  MAX(IF (hits.customVariables.index = 16, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv16Key,
  MAX(IF (hits.customVariables.index = 16, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv16Value,
  MAX(IF (hits.customVariables.index = 17, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv17Key,  
  MAX(IF (hits.customVariables.index = 17, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv17Value,    
  MAX(IF (hits.customVariables.index = 18, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv18Key,  
  MAX(IF (hits.customVariables.index = 18, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv18Value,    
  MAX(IF (hits.customVariables.index = 19, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv19Key,  
  MAX(IF (hits.customVariables.index = 19, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv19Value,    
  MAX(IF (hits.customVariables.index = 20, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv20Key,  
  MAX(IF (hits.customVariables.index = 20, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv20Value,    
  MAX(IF (hits.customVariables.index = 21, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv21Key,  
  MAX(IF (hits.customVariables.index = 21, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv21Value,    
  MAX(IF (hits.customVariables.index = 22, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv22Key,  
  MAX(IF (hits.customVariables.index = 22, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv22Value,    
  MAX(IF (hits.customVariables.index = 23, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv23Key,  
  MAX(IF (hits.customVariables.index = 23, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv23Value,    
  MAX(IF (hits.customVariables.index = 24, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv24Key,  
  MAX(IF (hits.customVariables.index = 24, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv24Value,    
  MAX(IF (hits.customVariables.index = 25, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv25Key,  
  MAX(IF (hits.customVariables.index = 25, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv25Value,    
  MAX(IF (hits.customVariables.index = 26, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv26Key,  
  MAX(IF (hits.customVariables.index = 26, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv26Value,    
  MAX(IF (hits.customVariables.index = 27, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv27Key,  
  MAX(IF (hits.customVariables.index = 27, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv27Value,    
  MAX(IF (hits.customVariables.index = 28, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv28Key,  
  MAX(IF (hits.customVariables.index = 28, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv28Value,    
  MAX(IF (hits.customVariables.index = 29, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv29Key,  
  MAX(IF (hits.customVariables.index = 29, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv29Value,    
  MAX(IF (hits.customVariables.index = 30, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv30Key,  
  MAX(IF (hits.customVariables.index = 30, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv30Value,    
  MAX(IF (hits.customVariables.index = 31, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv31Key,  
  MAX(IF (hits.customVariables.index = 31, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv31Value,    
  MAX(IF (hits.customVariables.index = 32, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv32Key,  
  MAX(IF (hits.customVariables.index = 32, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv32Value,    
  MAX(IF (hits.customVariables.index = 33, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv33Key,  
  MAX(IF (hits.customVariables.index = 33, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv33Value,    
  MAX(IF (hits.customVariables.index = 34, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv34Key,  
  MAX(IF (hits.customVariables.index = 34, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv34Value,    
  MAX(IF (hits.customVariables.index = 35, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv35Key,  
  MAX(IF (hits.customVariables.index = 35, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv35Value,    
  MAX(IF (hits.customVariables.index = 36, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv36Key,  
  MAX(IF (hits.customVariables.index = 36, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv36Value,    
  MAX(IF (hits.customVariables.index = 37, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv37Key,  
  MAX(IF (hits.customVariables.index = 37, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv37Value,    
  MAX(IF (hits.customVariables.index = 38, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv38Key,  
  MAX(IF (hits.customVariables.index = 38, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv38Value,    
  MAX(IF (hits.customVariables.index = 39, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv39Key,  
  MAX(IF (hits.customVariables.index = 39, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv39Value,    
  MAX(IF (hits.customVariables.index = 40, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv40Key,  
  MAX(IF (hits.customVariables.index = 40, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv40Value,    
  MAX(IF (hits.customVariables.index = 41, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv41Key,  
  MAX(IF (hits.customVariables.index = 41, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv41Value,    
  MAX(IF (hits.customVariables.index = 42, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv42Key,  
  MAX(IF (hits.customVariables.index = 42, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv42Value,    
  MAX(IF (hits.customVariables.index = 43, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv43Key,  
  MAX(IF (hits.customVariables.index = 43, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv43Value,    
  MAX(IF (hits.customVariables.index = 44, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv44Key,  
  MAX(IF (hits.customVariables.index = 44, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv44Value,    
  MAX(IF (hits.customVariables.index = 45, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv45Key,  
  MAX(IF (hits.customVariables.index = 45, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv45Value,    
  MAX(IF (hits.customVariables.index = 46, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv46Key,  
  MAX(IF (hits.customVariables.index = 46, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv46Value,    
  MAX(IF (hits.customVariables.index = 47, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv47Key,  
  MAX(IF (hits.customVariables.index = 47, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv47Value,    
  MAX(IF (hits.customVariables.index = 48, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv48Key,  
  MAX(IF (hits.customVariables.index = 48, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv48Value,    
  MAX(IF (hits.customVariables.index = 49, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv49Key,  
  MAX(IF (hits.customVariables.index = 49, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv49Value,    
  MAX(IF (hits.customVariables.index = 50, hits.customVariables.customVarName,  NULL)) WITHIN RECORD AS cv50Key,  
  MAX(IF (hits.customVariables.index = 50, hits.customVariables.customVarValue, NULL)) WITHIN RECORD AS cv50Value
FROM [dataset_id.ga_sessions_YYYYMMDD]